apiVersion: v1
kind: Pod
metadata:
  name: pod-y-db
  labels:
    app: critical-db
spec:
  containers:
  - name: postgres
    image: postgres:15-alpine
    env:
    - name: POSTGRES_PASSWORD
      value: "secret"
    readinessProbe:
      exec:
        command: ["pg_isready", "-U", "postgres"]
      periodSeconds: 5
      timeoutSeconds: 2
